# Movie Data Analysis & ETL

This project focuses on cleaning and preparing movie-related datasets for analysis.

The goal is to ensure data quality, consistency, and usability for further analytical tasks such as SQL querying and business intelligence.

Datasets included:
- Movies
- Reviews
- Cast
- Crew
- Genres

In [1]:
import pandas as pd

cast= pd.read_csv("cast.csv")
crew= pd.read_csv("crew.csv")
genres= pd.read_csv("genres.csv")
movies=pd.read_csv("movies.csv", encoding="utf-8",engine="python",quotechar='"',on_bad_lines="skip")
reviews=pd.read_csv("reviews.csv",sep=",", encoding="utf-8")

## Cast Dataset - Data Cleaning

### Overview
Dataset containing information about actors involved in each movie.

### Cleaning Steps
- Inspected dataset structure and columns
- Removed irrelevant columns if necessary
- Cleaned string values (strip)
- Handled missing values
- Ensured correct data types for identifiers (es. movie_release_date)

In [2]:
cast.shape
cast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150044 entries, 0 to 150043
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  150044 non-null  int64
 1   movie_id            150044 non-null  int64
 2   person_id           150044 non-null  int64
 3   name                150044 non-null  object
 4   character           142822 non-null  object
 5   cast_order          150044 non-null  int64
 6   movie_title         150044 non-null  object
 7   movie_release_date  149751 non-null  object
dtypes: int64(4), object(4)
memory usage: 9.2+ MB

In [3]:
cast.columns

Index(['id', 'movie_id', 'person_id', 'name', 'character', 'cast_order',
       'movie_title', 'movie_release_date'],
      dtype='object')

In [4]:
for col in cast.select_dtypes("object"):
    cast[col]= cast[col].str.strip()

In [5]:
cast.isna().sum()

id                       0
movie_id                 0
person_id                0
name                     0
character             7222
cast_order               0
movie_title              0
movie_release_date     293
dtype: int64

In [6]:
cast.duplicated().sum()

np.int64(0)

In [7]:
cast["movie_release_date"]=pd.to_datetime(cast["movie_release_date"])

In [8]:
cast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150044 entries, 0 to 150043
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  150044 non-null  int64
 1   movie_id            150044 non-null  int64
 2   person_id           150044 non-null  int64
 3   name                150044 non-null  object
 4   character           142822 non-null  object
 5   cast_order          150044 non-null  int64
 6   movie_title         150044 non-null  object
 7   movie_release_date  149751 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 9.2+ MB

## Crew Dataset - Data Cleaning

### Overview
Dataset containing information about crew members such as directors and producers.

### Cleaning Steps
- Explored dataset structure
- Removed unnecessary columns (e.g. homepage, tagline if present)
- Cleaned text columns
- Handled missing values
- Converted identifiers to correct data types

In [9]:
crew.shape
crew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63632 entries, 0 to 63631
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  63632 non-null  int64
 1   movie_id            63632 non-null  int64
 2   person_id           63632 non-null  int64
 3   name                63632 non-null  object
 4   job                 63632 non-null  object
 5   department          63632 non-null  object
 6   movie_title         63632 non-null  object
 7   movie_release_date  63302 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.9+ MB

In [10]:
crew.iloc[50:70]

,id,movie_id,person_id,name,job,department,movie_title,movie_release_date
50,3847,24,138,Quentin Tarantino,Writer,Writing,Kill Bill: Vol. 1,2003-10-10
51,52094,25,39,Sam Mendes,Director,Directing,Jarhead,2005-11-04
52,52095,25,135,Bobby Cohen,Executive Producer,Production,Jarhead,2005-11-04
53,52097,25,136,Sam Mercer,Executive Producer,Production,Jarhead,2005-11-04
54,52096,25,19862,Lucy Fisher,Producer,Production,Jarhead,2005-11-04
55,52098,25,931,Douglas Wick,Producer,Production,Jarhead,2005-11-04
56,52099,25,142,William Broyles Jr.,Screenplay,Writing,Jarhead,2005-11-04
57,6924,28,1776,Francis Ford Coppola,Director,Directing,Apocalypse Now,1979-05-19
58,6925,28,1776,Francis Ford Coppola,Producer,Production,Apocalypse Now,1979-05-19
59,6926,28,8328,John Milius,Writer,Writing,Apocalypse Now,1979-05-19
60,6927,28,1776,Francis Ford Coppola,Writer,Writing,Apocalypse Now,1979-05-19
61,17996,33,190,Clint Eastwood,Director,Directing,Unforgiven,1992-08-07
62,17997,33,3718,David Valdes,Executive Producer,Production,Unforgiven,1992-08-07
63,17998,33,190,Clint Eastwood,Producer,Production,Unforgiven,1992-08-07
64,17999,33,7191,David Webb Peoples,Writer,Writing,Unforgiven,1992-08-07
65,10248,35,197,David Silverman,Director,Directing,The Simpsons Movie,2007-07-25
66,10238,35,1128341,Nikki Vanzo,Executive Producer,Production,The Simpsons Movie,2007-07-25
67,10237,35,3388,James L. Brooks,Producer,Production,The Simpsons Movie,2007-07-25
68,10240,35,162931,Al Jean,Producer,Production,The Simpsons Movie,2007-07-25
69,10242,35,5741,Matt Groening,Producer,Production,The Simpsons Movie,2007-07-25

In [11]:
for col in crew.select_dtypes("object"):
    crew[col]= crew[col].str.strip()

In [12]:
crew["movie_release_date"]=pd.to_datetime(crew["movie_release_date"])

In [13]:
crew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63632 entries, 0 to 63631
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  63632 non-null  int64
 1   movie_id            63632 non-null  int64
 2   person_id           63632 non-null  int64
 3   name                63632 non-null  object
 4   job                 63632 non-null  object
 5   department          63632 non-null  object
 6   movie_title         63632 non-null  object
 7   movie_release_date  63302 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 3.9+ MB

In [14]:
crew.isna().sum()

id                      0
movie_id                0
person_id               0
name                    0
job                     0
department              0
movie_title             0
movie_release_date    330
dtype: int64

In [15]:
crew.duplicated().sum()

np.int64(0)

## Genres Dataset - Data Cleaning

### Overview
Dataset containing movie genres and category classifications.

### Cleaning Steps
- Inspected structure and columns
- Cleaned string values
- Handled missing values
- Ensured consistency in genre naming

In [16]:
genres.shape
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           19 non-null     int64
 1   name         19 non-null     object
 2   movie_count  19 non-null     int64
dtypes: int64(2), object(1)
memory usage: 588.0+ bytes

In [17]:
genres.head(19)

       id             name  movie_count
0      18            Drama         4334
1      35           Comedy         2777
2      53         Thriller         2172
3      28           Action         1967
4   10749          Romance         1384
5      27           Horror         1343
6      12        Adventure         1268
7      80            Crime         1170
8     878  Science Fiction         1010
9      14          Fantasy          867
10  10751           Family          779
11     16        Animation          680
12   9648          Mystery          650
13     36          History          354
14  10402            Music          354
15  10770         TV Movie          344
16     99      Documentary          288
17  10752              War          221
18     37          Western          141

## Movies Dataset - Data Cleaning

### Overview
Initial exploration of the dataset to understand its structure, data types, and content.

### Cleaning Steps
- Inspected dataset using head(), info(), and shape
- Removed unnecessary columns (e.g. poster_path, homepage)
- Trimmed whitespace from string columns
- Handled missing values and invalid entries
- Converted columns to appropriate data types (e.g. id, budget, revenue, vote_count, release_date)
- Treated zero values in financial columns as missing data

In [18]:
movies.shape
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9771 entries, 0 to 9770
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 9771 non-null   object
 1   title              9771 non-null   object
 2   original_title     9771 non-null   object
 3   overview           9611 non-null   object
 4   release_date       9710 non-null   object
 5   runtime            9770 non-null   float64
 6   budget             9770 non-null   float64
 7   revenue            9770 non-null   float64
 8   vote_average       9770 non-null   object
 9   vote_count         9770 non-null   object
 10  popularity         9770 non-null   object
 11  poster_path        9433 non-null   object
 12  backdrop_path      8252 non-null   object
 13  status             9770 non-null   object
 14  tagline            5968 non-null   object
 15  homepage           3434 non-null   object
 16  original_language  9770 non-null   object
 17  adult              9770 non-null   object
 18  video              9770 non-null   object
 19  created_at         9769 non-null   object
 20  updated_at         9769 non-null   object
 21  genres             9501 non-null   object
dtypes: float64(3), object(19)
memory usage: 1.6+ MB

In [19]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(movies.head(1))

  id  title original_title                                           overview  \
0  2  Ariel          Ariel  A Finnish man goes to the city to find a job a...

  release_date  runtime  budget  revenue vote_average vote_count popularity  \
0   1988-10-21     73.0     0.0      0.0        7.102        368     5.0295

                        poster_path                     backdrop_path  \
0  /ojDg0PGvs6R9xYFodRct2kdI6wC.jpg  /hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg

     status tagline homepage original_language adult video  \
0  Released     NaN      NaN                fi     0     0

            created_at                  updated_at                      genres
0  2026-02-13 12:09:05  2026-02-13T17:39:05.734678  Drama,Comedy,Crime,Romance

In [20]:
movies.columns

Index(['id', 'title', 'original_title', 'overview', 'release_date', 'runtime',
       'budget', 'revenue', 'vote_average', 'vote_count', 'popularity',
       'poster_path', 'backdrop_path', 'status', 'tagline', 'homepage',
       'original_language', 'adult', 'video', 'created_at', 'updated_at',
       'genres'],
      dtype='object')

In [21]:
movies.drop(columns=["original_title","backdrop_path","tagline","homepage","created_at","updated_at","adult","video"], inplace=True, errors='ignore')

In [22]:
movies.columns

Index(['id', 'title', 'overview', 'release_date', 'runtime', 'budget',
       'revenue', 'vote_average', 'vote_count', 'popularity', 'poster_path',
       'status', 'original_language', 'genres'],
      dtype='object')

In [23]:
movies.head()

,id,title,overview,release_date,runtime,budget,revenue,vote_average,vote_count,popularity,poster_path,status,original_language,genres
0,2,Ariel,A Finnish man goes to the city to find a job a...,1988-10-21,73.0,0.0,0.0,7.102,368,5.0295,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,Released,fi,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,11000000.0,775398007.0,8.202,21922,23.1666,/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg,Released,en,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",2003-05-30,100.0,94000000.0,940335536.0,7.817,20256,15.7935,/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg,Released,en,"Animation,Family"
3,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.0,55000000.0,677387716.0,8.462,29226,22.7297,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,Released,en,"Drama,Comedy,Romance"
4,14,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,122.0,15000000.0,356296601.0,8.002,12792,8.6764,/wby9315QzVKdW9BonAefg8jGTTb.jpg,Released,en,Drama

In [24]:
movies["release_date"] = pd.to_datetime(movies["release_date"], errors="coerce")

In [25]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9771 entries, 0 to 9770
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 9771 non-null   object
 1   title              9771 non-null   object
 2   overview           9611 non-null   object
 3   release_date       9709 non-null   datetime64[ns]
 4   runtime            9770 non-null   float64
 5   budget             9770 non-null   float64
 6   revenue            9770 non-null   float64
 7   vote_average       9770 non-null   object
 8   vote_count         9770 non-null   object
 9   popularity         9770 non-null   object
 10  poster_path        9433 non-null   object
 11  status             9770 non-null   object
 12  original_language  9770 non-null   object
 13  genres             9501 non-null   object
dtypes: datetime64[ns](1), float64(3), object(10)
memory usage: 1.0+ MB

In [33]:
movies["id"]= movies["id"].astype(int)
movies["vote_average"]= movies["vote_average"].astype(float)
movies["vote_count"]= movies["vote_count"].astype(int)
movies["popularity"]= movies["popularity"].astype(float)

In [27]:
movies[~movies["id"].astype(str).str.isnumeric()]["id"]

6131     Of the domestic exploration for finding my vo...
Name: id, dtype: object

In [28]:
movies["id"] = pd.to_numeric(movies["id"], errors="coerce")

In [29]:
movies.isna().sum()

id                     1
title                  0
overview             160
release_date          62
runtime                1
budget                 1
revenue                1
vote_average           1
vote_count             1
popularity             1
poster_path          338
status                 1
original_language      1
genres               270
dtype: int64

In [30]:
movies = movies.dropna(subset=["id","status"])

In [31]:
movies.duplicated().sum()

np.int64(0)

In [32]:
movies["budget"] = movies["budget"].replace(0, pd.NA)
movies["revenue"] = movies["revenue"].replace(0, pd.NA)

In [ ]:
for col in movies.select_dtypes("object"):
    movies[col]=movies[col].str.strip()

AttributeError: Can only use .str accessor with string values!

## Reviews Dataset - Data Cleaning

### Overview
Exploration of review data including structure and text fields.

### Cleaning Steps
- Checked dataset structure and columns
- Removed unnecessary columns if present
- Trimmed text fields to remove extra spaces
- Handled missing values
- Ensured consistency of review-related fields

In [ ]:
reviews.shape
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13073 entries, 0 to 13072
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  13073 non-null  object
 1   movie_id            13073 non-null  int64
 2   author              13073 non-null  object
 3   author_username     13073 non-null  object
 4   author_rating       11639 non-null  float64
 5   content             13073 non-null  object
 6   created_at          13073 non-null  object
 7   updated_at          13073 non-null  object
 8   url                 13073 non-null  object
 9   movie_title         13073 non-null  object
 10  movie_release_date  13073 non-null  object
 11  movie_rating        13073 non-null  float64
 12  content_length      13073 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 1.3+ MB

In [ ]:
reviews["movie_release_date"]=pd.to_datetime(reviews["movie_release_date"])

In [ ]:
reviews.head()

,id,movie_id,author,author_username,author_rating,content,created_at,updated_at,url,movie_title,movie_release_date,movie_rating,content_length
0,58a231c5925141179e000674,11,Cat Ellington,CatEllington,NaN,"(As I'm writing this review, Darth Vader's the...",2017-02-13T22:23:01.268Z,2021-06-23T15:57:53.915Z,https://www.themoviedb.org/review/58a231c59251...,Star Wars,1977-05-25,8.202,3429
1,5d340e7a2f8d090388d21ff2,11,John Chard,John Chard,10.0,A long time ago in a childhood not too far awa...,2019-07-21T07:04:26.939Z,2024-05-16T15:22:23.643Z,https://www.themoviedb.org/review/5d340e7a2f8d...,Star Wars,1977-05-25,8.202,2979
2,5e94ea4566565a0014baa6c5,11,gastyny,gastyny,10.0,Star Wars (1977) is a true masterpiece of cine...,2020-04-13T22:40:05.539Z,2021-06-23T15:58:36.846Z,https://www.themoviedb.org/review/5e94ea456656...,Star Wars,1977-05-25,8.202,564
3,60174e821b70ae003c643834,11,r96sk,r96sk,9.0,A quality start to the franchise.\r\n\r\nI say...,2021-02-01T00:42:42.135Z,2021-06-23T15:58:50.959Z,https://www.themoviedb.org/review/60174e821b70...,Star Wars,1977-05-25,8.202,1269
4,63c2163f05a53300e99bfdd1,11,GenerationofSwine,GenerationofSwine,10.0,Everyone and their mother is going to write re...,2023-01-14T02:41:03.836Z,2023-01-14T02:41:03.886Z,https://www.themoviedb.org/review/63c2163f05a5...,Star Wars,1977-05-25,8.202,2294

In [ ]:
reviews.drop(columns=["author_username","content","created_at","updated_at","url"],inplace=True)

In [ ]:
reviews.columns

Index(['id', 'movie_id', 'author', 'author_rating', 'movie_title',
       'movie_release_date', 'movie_rating', 'content_length'],
      dtype='object')

In [ ]:
reviews.isna().sum()

id                       0
movie_id                 0
author                   0
author_rating         1434
movie_title              0
movie_release_date       0
movie_rating             0
content_length           0
dtype: int64

In [ ]:
reviews.duplicated().sum()

np.int64(0)

In [ ]:
for col in reviews.select_dtypes("object"):
    reviews[col]=reviews[col].str.strip()

## Genre Transformation

In this step, the original `genres` column from the movies dataset is transformed into a normalized structure suitable for relational analysis.

### Process

- Selected only relevant columns (`id`, `genres`)
- Removed rows with missing genre values
- Renamed `id` to `movie_id` for consistency
- Split multiple genres into lists using comma separation
- Expanded the dataset so that each row contains a single genre per movie
- Cleaned genre names by removing extra spaces
- Renamed the column to `genre_name`
- Removed duplicate records
- Reset the index for a clean structure
- Converted `movie_id` to integer type

### Result

The resulting dataset contains a normalized many-to-one relationship between movies and genres, making it suitable for SQL joins and analytical queries.

### Output

The cleaned dataset is exported as:

`genre_film_clear.csv`

In [36]:
movie = pd.read_csv("File puliti\movies_clean.csv", encoding="utf-8")
genre_film = movie[["id", "genres"]].copy()
genre_film = genre_film.dropna(subset=["genres"])
genre_film = genre_film.rename(columns={"id": "movie_id"})
genre_film["genres"] = genre_film["genres"].str.split(",")
genre_film = genre_film.explode("genres")
genre_film["genres"] = genre_film["genres"].str.strip()
genre_film = genre_film.rename(columns={"genres": "genre_name"})
genre_film = genre_film.drop_duplicates()
genre_film = genre_film.reset_index(drop=True)
genre_film['movie_id']=genre_film['movie_id'].astype(int)
genre_film.to_csv("genre_film_clear.csv", index=False, encoding="utf-8")

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\Utente\AppData\Local\Temp\ipykernel_1828\2717539170.py:1: SyntaxWarning: invalid escape sequence '\m'
  movie = pd.read_csv("File puliti\movies_clean.csv", encoding="utf-8")

## Data Consistency & Relationships

After cleaning individual datasets, consistency checks were performed across all tables.

- Standardized column names (lowercase, trimmed)
- Ensured consistent data types across datasets
- Verified key relationships (e.g. movie_id linking movies, cast, crew, and reviews)
- Checked for mismatches between related datasets

## Data Export

In this final step, the cleaned and transformed datasets are exported as CSV files.

These files will be used for:
- SQL database integration
- Further data analysis
- Business Intelligence tools (e.g. Power BI, Looker)

This step completes the ETL process, making the data ready for downstream applications.

In [37]:
import pandas as pd
from sqlalchemy import create_engine

#connessione MySQL
engine = create_engine("mysql+pymysql://root:211100@localhost/Movies_Database")

# carica csv
cast = pd.read_csv("File puliti\cast_clean.csv")
crew = pd.read_csv("File puliti\crew_clean.csv")
genres=pd.read_csv("File puliti\genres_clean.csv")
movies= pd.read_csv("File puliti\movies_clean.csv")
reviews= pd.read_csv("File puliti/reviews_clean.csv")

#invia a MySQL
cast.to_sql("cast_clean", con=engine, if_exists="replace", index=False)
crew.to_sql("crew_clean", con=engine, if_exists="replace", index=False)
genres.to_sql("genres_clean", con=engine, if_exists="replace", index=False)
movies.to_sql("movies_clean", con=engine, if_exists="replace", index=False)
reviews.to_sql("reviews_clean", con=engine, if_exists="replace", index=False)
genre_film.to_sql("genre_film_clean", con=engine, if_exists="replace", index=False)

<>:8: SyntaxWarning: invalid escape sequence '\c'
<>:9: SyntaxWarning: invalid escape sequence '\c'
<>:10: SyntaxWarning: invalid escape sequence '\g'
<>:11: SyntaxWarning: invalid escape sequence '\m'
<>:8: SyntaxWarning: invalid escape sequence '\c'
<>:9: SyntaxWarning: invalid escape sequence '\c'
<>:10: SyntaxWarning: invalid escape sequence '\g'
<>:11: SyntaxWarning: invalid escape sequence '\m'
C:\Users\Utente\AppData\Local\Temp\ipykernel_1828\2658719426.py:8: SyntaxWarning: invalid escape sequence '\c'
  cast = pd.read_csv("File puliti\cast_clean.csv")
C:\Users\Utente\AppData\Local\Temp\ipykernel_1828\2658719426.py:9: SyntaxWarning: invalid escape sequence '\c'
  crew = pd.read_csv("File puliti\crew_clean.csv")
C:\Users\Utente\AppData\Local\Temp\ipykernel_1828\2658719426.py:10: SyntaxWarning: invalid escape sequence '\g'
  genres=pd.read_csv("File puliti\genres_clean.csv")
C:\Users\Utente\AppData\Local\Temp\ipykernel_1828\2658719426.py:11: SyntaxWarning: invalid escape sequence '\m'
  movies= pd.read_csv("File puliti\movies_clean.csv")

22102

## Final Dataset

The cleaned and transformed datasets are now ready for:

- SQL database integration
- Data analysis
- Business intelligence tools (Power BI / Looker)

All datasets have been standardized and prepared for relational analysis.